### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [androidthings/drivers-samples#14]

**Comment by Fleker** [comment]
Try rebooting your device and seeing whether that works.

**Comment by kaka120011** [comment]
Version 0.5 must work on version 0.5

**Comment by itamar6587** [comment]
HI, How did you solve this issue? 
I'm having the same problems..

**Comment by mangini** [comment]
@itamar6587 Make sure the version of Android Things flashed on your board matches the version of the SDK used on your code and on the driver. If you are testing this sample on a board flashed with pre-0.5, the MANAGE_SENSOR_DRIVERS permissions [didn't exist at that time](https://developer.android.com/things/preview/releases.html#user_driver_permissions), and it can cause an exception similar to what you are getting.

**Comment by itamar6587** [comment]
@mangini  thanks for your reply. I'll check it. thanks

**Comment by Danielx303** [comment]
Also - this thing can help you - please add 2 things to your Android Manifest file: 
```
<uses-permission android:name="com.google.android.things.permission.MANAGE_INPUT_DRIVERS" />
<uses-permission android:name="com.google.android.things.permission.USE_PERIPHERAL_IO"/>
```
