### ISSUE TITLE
PWMServo sample not working with Raspberry Pi 3

### ISSUE THREAD

**Issue by rno** [androidthings/drivers-samples#2]
Hello,

I can't get the [pwmservo](https://github.com/androidthings/drivers-samples/tree/master/pwmservo) sample running. The servo I'm using works properly (I tried with an Arduino Uno).

As a side note, I also tried the other [pwn sample](https://github.com/androidthings/sample-simplepio/tree/master/pwm) without success.

**Comment by proppy** [comment]
@rno can you share a picture on how you wired the servo to the Raspberry Pi?

**Comment by rno** [comment]
@proppy, here's the picture of my wiring:

![img_20161220_072649](https://cloud.githubusercontent.com/assets/53433/21351045/a7bcc45e-c688-11e6-9001-ecdb4e723e6f.jpg)

Sorry for the cables colors not matching the ones from the servo, that the only ones left I have.

**Comment by jdkoren** [comment]
@rno The wiring looks correct to me. You may have to change some code in the sample app to match the specifications of the servo; in particular, you may need to call `setPulseDurationRange(0.5, 2.5)` based on the technical details [listed here](https://www.adafruit.com/product/154). Can you give that a try and let us know if that helps?

**Comment by rno** [comment]
Hi @jdkoren, it still does not work for me :-/

**Comment by jdkoren** [comment]
@rno Do you have another Servo you can try? Perhaps you can also try a different PWM pin?

**Comment by rno** [comment]
Ok, I just removed a servo from another project to test it and it works.

I still don't understand why the other one is not working even though it's working fine on the Arduino...

Sorry for the trouble and thanks a lot for your help!

**Comment by proppy** [comment]
@rno can you tell us which servo library (if any) you were using w/ the UNO?

**Comment by rno** [comment]
@proppy, I'm using the arduino servo library, without changing the min and max (it worked out of the box).

Sorry for replying only now.
